# Generated by Django 3.2.10 on 2022-01-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0006_companyinfo2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo2',
        ),
    ]
