# Generated by Django 3.2.10 on 2022-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0007_delete_companyinfo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='eventid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='companyid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='skills',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
