# Generated by Django 3.2.10 on 2022-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0009_alter_eventinfo_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='eventid',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='eventid',
            field=models.CharField(default='4', max_length=200),
            preserve_default=False,
        ),
    ]
