# Generated by Django 3.2.10 on 2022-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0010_auto_20220124_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
