# Generated by Django 3.2.10 on 2022-01-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0011_eventinfo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinfo',
            old_name='email',
            new_name='email1',
        ),
    ]
